### PR TITLE
Better git error

### PR DESCRIPTION
**Pull request by badboy**
A nice and long error message and fetching the git author name the same way real git does it.
I'm not 100% happy with the code and the error message could be improved as well.

### CODE REVIEW

**Comment by badboy** [comment]
It should have a test before merging.

Also: We need better error handling. `String` is really not that good here. Will work on that before this is ready.

**Comment by schultyy** [comment]
@badboy Can this be merged or is there work to be done first?

**Comment by badboy** [comment]
I'm not 100% satisfied with the user-visible error message. Gonna rewrite that and then merge it

**Comment by badboy** [comment]
3256a8c2c430a93a99b4be94fcca08c78560894c now has a much nicer error message, which I took from `man git-commit-tree` (and slightly modified).

14ad9f0303145b7a92e6f80194220b9aae2f910c removes support for the `GIT_AUTHOR_*` variables as I think it is too confusing and a single variable per setting is good enough.

If you agree with all (and tests are green): Ready to merge.

**Comment by badboy** [comment]
Forgot to remove one sentence, fixed in b278629b8a03cb9094e29344484396dc9635ad22

**Pull request merged**
