### PR TITLE
feat: Add support for major zero-style initial development

### LINKED ISSUE #137: Incorrect bump when major is v0
If a project is on, say, `v0.2.0` and you have a breaking change-commit, running `semantic-rs` suggests the new version should now be `v1.0.0`:

```
$ semantic-rs -w=no -r=no

semantic.rs 🚀
Performing preflight checks now
Checks done. Everything is ok
Current version: 0.2.0
Analyzing commits
Commits analyzed. Bump would be Major
New version would be: 1.0.0
```

But according to http://semver.org, you bump the 2nd component for breaking changes when you are at major v0

*Expected*: `v0.2.0` -> `v0.3.0`
*Actual*: `v0.2.0` -> `v1.0.0`

### PR DESCRIPTION
**Pull request by mandrean**
This PR adds support for major zero as outlined in http://semver.org.

Basically, breaking changes bumps the minor component and all other changes bumps the patch. Major is kept at zero.

Fixes #137.

### CODE REVIEW

**Comment by mandrean** [comment]
Travis CI fails for some reason:
image

image

**Comment by mandrean** [comment]
Ah I see. The test fixture for `initial-release` & `write-mode` assumes that it would go from `0.1.0` to `1.0.0`.

I updated them to go from `0.0.0` to `0.1.0` & `0.1.0` to `0.2.0`, respectively.

Tests are green now!

**Comment by mersinvald** [comment]
+1 for that, it's a natural improvement for Rust ecosystem

**Review by matchai — APPROVED** [review]

**Comment by stepankuzmin** [comment]
Any chances for this PR to be merged?

**Comment by mikenholt** [comment]
Is there a reason this can't be merged?

**Comment by thoward27** [comment]
Any blockers here? We would greatly benefit from this being merged, I am willing to help alleviate any potential blocks

**Comment by naturallymitchell** [comment]
I encourage this development.

**Review by PsiACE — APPROVED** [review]
I support the PR to be merged.

**Comment by mandrean** [comment]
Anyone with write access who can have a look at this? @schultyy @badboy

**Pull request closed without merging**
