### PR TITLE
feat: Allow write mode to be disabled, even on CI

### PR DESCRIPTION
**Pull request by badboy**
This tackles #68.

It adds a new `--no-write` flag, mutually exclusive to `--write`.
If either one is passed, we adhere to it, otherwise we determine write status based on whether `CI` is set or not.
This allows to explicitely disable write mode on CI environments, without unsetting the variable.
There is another issue now, that is we wait for other builds if `CI` is set, even though we know we're not gonna write (or release anything).

Should we make this "wait for CI" only in write & release mode?

### CODE REVIEW

**Comment by badboy** [comment]
Oh, I see now we're using `--release=[yes|no]`, but now `--no-write`. We should be consistent with naming, so which one is better? /cc @schu

**Comment by badboy** [comment]
I added commits to disable "wait for CI" if not in release mode and made sure release mode is disabled if write mode is disabled.
This also allows to re-enable a test.

Only thing left now is the flag writing.

**Comment by schultyy** [comment]
I would go for `--release=[yes|no]` instead of `--no-write` here.

**Comment by schultyy** [comment]
Do we need to do something here? Or can this be merged?

**Comment by badboy** [comment]
I'll take a look this weekend.

**Comment by badboy** [comment]
I guess I have to rebase…

**Comment by badboy** [comment]
Rebased.

**Comment by badboy** [comment]
I'll change to `--write=no|yes` now, then merge

**Comment by badboy** [comment]
We can iterate on the exact behaviour after the merge

**Comment by badboy** [comment]
I changed to chings:

1. Now using `--write=yes|no`
This means a single passed `-w` is not enough anymore. Either we need CI set or need to pass `--write=yes` to enable it. Sadly docopts has no way to have `-w` mean `-w yes` by default
2. Make the help output consistent (using uppercase letters for arguments)

**Pull request merged**
