### PR TITLE
Chore: Update dependencies

### PR DESCRIPTION
**Pull request by schultyy**
This PR is smoothing the way for future features by updating a bunch of dependencies.

*Note*: We now require at least Rust 1.15 to compile semantic-rs. A note in the README has been made about that.

### CODE REVIEW

**Comment by badboy** [comment]
This needs https://github.com/softprops/hubcaps/pull/64, which hopefully lands soon.
And also upgrades to our own git and hyper usage. Will take care of the latter now.

**Comment by badboy** [comment]
I added two commit: bumping the versions and fixing a minor thing needed for new hubcaps. New hubcaps is not yet released, so I'll wait for its release

**Comment by ebkalderon** [comment]
Looks like `hubcaps ` has been updated quite a few times since this PR was last edited. Is this project still being developed? I'm considering adopting it for my own projects.

**Comment by badboy** [comment]
@ebkalderon we can't dedicate as much time as we'd like to this project, but we'd still like to work on it eventually. Help is welcome.
I take a look at it later for the dependency upgrades.

**Comment by badboy** [comment]
Updated hubcaps. Let's see if tests pass. Will need confirmation from macos as well (I'll try to add a travis target for that as well)

**Comment by badboy** [comment]
Added macos target and it looks fine. Merging.

**Pull request merged**
